set(_SOURCES
        Logger/ExternalLogger.cpp
        Logger/FlightLogger.cpp
        Logger/GlueFlightLogger.cpp
        Logger/GlueLogbook.cpp
        Logger/Logbook.cpp
        Logger/LogbookBuilder.cpp
        Logger/LogbookPlace.cpp
        Logger/LogbookRecorder.cpp
        Logger/LogbookReplay.cpp
        Logger/GRecord.cpp
        Logger/Logger.cpp
        Logger/LoggerEPE.cpp
        Logger/LoggerFRecord.cpp
        Logger/LoggerImpl.cpp
        Logger/NMEALogger.cpp
        Logger/Settings.cpp
)

set(SCRIPT_FILES
    CMakeSource.cmake
)
