// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright The XCSoar Project

// Generated by tracing the vario display artwork into polygon
// contours - do not edit by hand.  Coordinates live in a box
// normalized to +-500 on the longer side, y growing downward; a
// "hole" contour is painted in the background color on top of the
// fill.  GLYPH_WIDTH/HEIGHT give the glyph's bounding box in the
// same 1000 units.

#pragma once

#include "ui/dim/Point.hpp"

#include <cstddef>
#include <span>

struct GlyphContour {
  const PixelPoint *pts;
  std::size_t n;
  bool hole;
};

using Glyph = std::span<const GlyphContour>;

/* spiral.png, 749x1000 */
inline constexpr PixelPoint VD_GLYPH_SPIRAL_C0[] = {
  {-26,-500}, {-74,-500}, {-85,-477}, {-137,-475}, {-166,-450}, {-312,-425},
  {-325,-389}, {-116,-178}, {-99,-191}, {-101,-237}, {-68,-272}, {-16,-277},
  {14,-252}, {85,-252}, {164,-201}, {210,-201}, {247,-156}, {210,-124},
  {64,-99}, {34,-74}, {-112,-74}, {-141,-49}, {-262,-49}, {-291,-24},
  {-337,-24}, {-375,3}, {-375,72}, {-287,124}, {-216,124}, {-187,149},
  {-91,149}, {-62,174}, {34,174}, {64,199}, {185,224}, {249,291}, {110,352},
  {14,352}, {-16,377}, {-187,377}, {-227,446}, {-197,500}, {-76,500},
  {-59,475}, {87,475}, {116,450}, {187,450}, {216,425}, {266,423}, {375,323},
  {375,252}, {293,156}, {187,101}, {41,76}, {-24,41}, {-9,22}, {112,24},
  {141,-1}, {187,-1}, {318,-55}, {375,-126}, {375,-199}, {352,-210},
  {343,-245}, {212,-325}, {166,-325}, {62,-375}, {-18,-379}, {-49,-410},
  {-26,-442},
};
inline constexpr GlyphContour VD_GLYPH_SPIRAL[] = {
  { VD_GLYPH_SPIRAL_C0, std::size(VD_GLYPH_SPIRAL_C0), false },
};
inline constexpr unsigned VD_GLYPH_SPIRAL_WIDTH = 749;
inline constexpr unsigned VD_GLYPH_SPIRAL_HEIGHT = 1000;

/* straight.png, 1000x669 */
inline constexpr PixelPoint VD_GLYPH_STRAIGHT_C0[] = {
  {-500,-298}, {-500,-240}, {-391,-142}, {-177,-31}, {63,142}, {68,212},
  {4,279}, {46,329}, {500,334}, {288,-97}, {247,-97}, {188,-3}, {121,0},
  {-386,-334}, {-450,-334},
};
inline constexpr GlyphContour VD_GLYPH_STRAIGHT[] = {
  { VD_GLYPH_STRAIGHT_C0, std::size(VD_GLYPH_STRAIGHT_C0), false },
};
inline constexpr unsigned VD_GLYPH_STRAIGHT_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_STRAIGHT_HEIGHT = 669;

/* sat.png, 1000x1000 */
inline constexpr PixelPoint VD_GLYPH_SAT_C0[] = {
  {-255,-500}, {-463,-281}, {-463,-238}, {-226,4}, {-261,45}, {-255,73},
  {-73,255}, {-45,261}, {-10,229}, {13,232}, {238,463}, {281,463}, {500,255},
  {500,195}, {261,-33}, {324,-99}, {324,-143}, {143,-324}, {99,-324},
  {33,-261}, {-195,-500},
};
inline constexpr PixelPoint VD_GLYPH_SAT_C1[] = {
  {218,13}, {249,22}, {437,218}, {428,249}, {267,402}, {235,393}, {48,197},
  {56,166},
};
inline constexpr PixelPoint VD_GLYPH_SAT_C2[] = {
  {-232,-437}, {-200,-428}, {-13,-232}, {-22,-200}, {-183,-48}, {-215,-56},
  {-402,-252}, {-393,-284},
};
inline constexpr PixelPoint VD_GLYPH_SAT_C3[] = {
  {-500,85}, {-500,255}, {-442,298}, {-425,353}, {-353,425}, {-298,442},
  {-255,500}, {-85,500}, {-105,468}, {-169,468}, {-324,388}, {-393,316},
  {-468,169}, {-468,105},
};
inline constexpr PixelPoint VD_GLYPH_SAT_C4[] = {
  {-356,128}, {-356,215}, {-206,362}, {-131,359}, {-128,336}, {-186,318},
  {-318,186}, {-333,131},
};
inline constexpr GlyphContour VD_GLYPH_SAT[] = {
  { VD_GLYPH_SAT_C0, std::size(VD_GLYPH_SAT_C0), false },
  { VD_GLYPH_SAT_C1, std::size(VD_GLYPH_SAT_C1), true },
  { VD_GLYPH_SAT_C2, std::size(VD_GLYPH_SAT_C2), true },
  { VD_GLYPH_SAT_C3, std::size(VD_GLYPH_SAT_C3), false },
  { VD_GLYPH_SAT_C4, std::size(VD_GLYPH_SAT_C4), false },
};
inline constexpr unsigned VD_GLYPH_SAT_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_SAT_HEIGHT = 1000;

/* glider.png, 1000x446 */
inline constexpr PixelPoint VD_GLYPH_GLIDER_C0[] = {
  {-500,-49}, {-500,-18}, {-493,-31}, {-28,-31}, {-9,176}, {-75,193},
  {-85,204}, {-85,223}, {85,223}, {85,204}, {75,193}, {9,176}, {29,-31},
  {493,-31}, {500,-18}, {495,-57}, {453,-76}, {319,-90}, {29,-90}, {23,-189},
  {4,-223}, {-13,-213}, {-23,-189}, {-29,-90}, {-386,-85}, {-471,-72},
};
inline constexpr PixelPoint VD_GLYPH_GLIDER_C1[] = {
  {-491,-49}, {-471,-67}, {-386,-80}, {-24,-81}, {-18,-190}, {2,-219},
  {18,-190}, {24,-81}, {386,-80}, {485,-62}, {491,-39}, {24,-40}, {4,180},
  {66,193}, {80,203}, {80,216}, {-77,219}, {-74,197}, {-4,180}, {-23,-39},
  {-487,-36},
};
inline constexpr GlyphContour VD_GLYPH_GLIDER[] = {
  { VD_GLYPH_GLIDER_C0, std::size(VD_GLYPH_GLIDER_C0), false },
  { VD_GLYPH_GLIDER_C1, std::size(VD_GLYPH_GLIDER_C1), true },
};
inline constexpr unsigned VD_GLYPH_GLIDER_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_GLIDER_HEIGHT = 446;

/* north.png, 1000x833 */
inline constexpr PixelPoint VD_GLYPH_NORTH_C0[] = {
  {-500,-416}, {-500,-352}, {-444,-347}, {-400,-297}, {-400,297}, {-444,347},
  {-500,352}, {-500,416}, {-135,416}, {-138,364}, {-191,347}, {-235,297},
  {-238,-96}, {-221,-116}, {-104,-7}, {-93,40}, {63,194}, {74,241},
  {238,416}, {400,416}, {400,-297}, {444,-347}, {500,-352}, {500,-416},
  {135,-416}, {138,-364}, {191,-347}, {235,-297}, {238,63}, {221,82},
  {104,-26}, {93,-74}, {-63,-227}, {-74,-274}, {-205,-416},
};
inline constexpr GlyphContour VD_GLYPH_NORTH[] = {
  { VD_GLYPH_NORTH_C0, std::size(VD_GLYPH_NORTH_C0), false },
};
inline constexpr unsigned VD_GLYPH_NORTH_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_NORTH_HEIGHT = 833;

/* small_glider.png, 1000x428 */
inline constexpr PixelPoint VD_GLYPH_SMALL_GLIDER_C0[] = {
  {-500,-57}, {-500,1}, {-477,-15}, {-48,-14}, {-42,49}, {-14,80}, {-14,148},
  {-38,172}, {-80,173}, {-115,214}, {115,214}, {80,173}, {38,172}, {14,148},
  {14,80}, {42,49}, {48,-14}, {477,-15}, {500,1}, {500,-57}, {449,-58},
  {436,-85}, {352,-85}, {336,-100}, {66,-100}, {42,-123}, {42,-178},
  {15,-191}, {14,-214}, {-14,-214}, {-15,-191}, {-41,-181}, {-42,-123},
  {-66,-100}, {-336,-100}, {-352,-85}, {-436,-85}, {-452,-57},
};
inline constexpr GlyphContour VD_GLYPH_SMALL_GLIDER[] = {
  { VD_GLYPH_SMALL_GLIDER_C0, std::size(VD_GLYPH_SMALL_GLIDER_C0), false },
};
inline constexpr unsigned VD_GLYPH_SMALL_GLIDER_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_SMALL_GLIDER_HEIGHT = 428;

/* avg_climb_rate.png, 797x1000 */
inline constexpr PixelPoint VD_GLYPH_AVG_CLIMB_C0[] = {
  {199,-500}, {165,-500}, {121,-369}, {79,-400}, {-49,-400}, {-224,-328},
  {-326,-225}, {-399,-83}, {-399,81}, {-365,117}, {-365,181}, {-196,358},
  {-232,417}, {-215,497}, {-174,489}, {-121,367}, {-79,397}, {82,397},
  {118,364}, {188,361}, {365,181}, {365,117}, {399,81}, {399,-83},
  {365,-119}, {362,-189}, {199,-356}, {229,-447},
};
inline constexpr PixelPoint VD_GLYPH_AVG_CLIMB_C1[] = {
  {182,-269}, {335,-83}, {335,81}, {224,261}, {82,333}, {-82,333},
  {-104,292}, {65,-53}, {65,-117}, {135,-256},
};
inline constexpr PixelPoint VD_GLYPH_AVG_CLIMB_C2[] = {
  {54,-333}, {68,-219}, {-32,-50}, {-32,14}, {-132,183}, {-135,253},
  {-182,267}, {-335,81}, {-301,-150}, {-149,-303},
};
inline constexpr GlyphContour VD_GLYPH_AVG_CLIMB[] = {
  { VD_GLYPH_AVG_CLIMB_C0, std::size(VD_GLYPH_AVG_CLIMB_C0), false },
  { VD_GLYPH_AVG_CLIMB_C1, std::size(VD_GLYPH_AVG_CLIMB_C1), true },
  { VD_GLYPH_AVG_CLIMB_C2, std::size(VD_GLYPH_AVG_CLIMB_C2), true },
};
inline constexpr unsigned VD_GLYPH_AVG_CLIMB_WIDTH = 797;
inline constexpr unsigned VD_GLYPH_AVG_CLIMB_HEIGHT = 1000;

/* roll_left.png, 1000x656 */
inline constexpr PixelPoint VD_GLYPH_ROLL_LEFT_C0[] = {
  {367,-328}, {346,-328}, {262,-235}, {82,-93}, {-42,51}, {-106,58},
  {-498,323}, {-436,307}, {-87,77}, {-8,93}, {19,61}, {3,23},
};
inline constexpr PixelPoint VD_GLYPH_ROLL_LEFT_C1[] = {
  {373,-193}, {423,-68}, {423,26}, {436,35}, {444,-66}, {402,-169},
};
inline constexpr PixelPoint VD_GLYPH_ROLL_LEFT_C2[] = {
  {-43,13}, {-117,-51}, {-84,-116}, {-212,-13}, {-201,-2}, {-167,-37},
  {-129,-40}, {-72,16},
};
inline constexpr GlyphContour VD_GLYPH_ROLL_LEFT[] = {
  { VD_GLYPH_ROLL_LEFT_C0, std::size(VD_GLYPH_ROLL_LEFT_C0), false },
  { VD_GLYPH_ROLL_LEFT_C1, std::size(VD_GLYPH_ROLL_LEFT_C1), false },
  { VD_GLYPH_ROLL_LEFT_C2, std::size(VD_GLYPH_ROLL_LEFT_C2), false },
};
inline constexpr unsigned VD_GLYPH_ROLL_LEFT_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_ROLL_LEFT_HEIGHT = 656;

/* roll_right.png, 1000x648 */
inline constexpr PixelPoint VD_GLYPH_ROLL_RIGHT_C0[] = {
  {-335,-324}, {-124,-106}, {-100,-100}, {15,13}, {1,38}, {7,81}, {81,64},
  {500,319}, {458,271}, {114,60}, {92,2}, {126,-44}, {61,-7}, {75,24},
  {61,44}, {-24,-61}, {-216,-216}, {-315,-324},
};
inline constexpr PixelPoint VD_GLYPH_ROLL_RIGHT_C1[] = {
  {114,-98}, {157,-47}, {222,-15}, {180,-63},
};
inline constexpr PixelPoint VD_GLYPH_ROLL_RIGHT_C2[] = {
  {-378,-137}, {-409,-90}, {-401,-30}, {-370,-112},
};
inline constexpr PixelPoint VD_GLYPH_ROLL_RIGHT_C3[] = {
  {-301,-248}, {-350,-208}, {-367,-160}, {-336,-182},
};
inline constexpr GlyphContour VD_GLYPH_ROLL_RIGHT[] = {
  { VD_GLYPH_ROLL_RIGHT_C0, std::size(VD_GLYPH_ROLL_RIGHT_C0), false },
  { VD_GLYPH_ROLL_RIGHT_C1, std::size(VD_GLYPH_ROLL_RIGHT_C1), false },
  { VD_GLYPH_ROLL_RIGHT_C2, std::size(VD_GLYPH_ROLL_RIGHT_C2), false },
  { VD_GLYPH_ROLL_RIGHT_C3, std::size(VD_GLYPH_ROLL_RIGHT_C3), false },
};
inline constexpr unsigned VD_GLYPH_ROLL_RIGHT_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_ROLL_RIGHT_HEIGHT = 648;

/* battery.png, 555x1000 */
inline constexpr PixelPoint VD_GLYPH_BATTERY_C0[] = {
  {-188,-466}, {-277,-405}, {-277,443}, {-220,500}, {220,500}, {277,443},
  {274,-414}, {85,-500}, {-85,-500},
};
inline constexpr PixelPoint VD_GLYPH_BATTERY_C1[] = {
  {-228,-394}, {237,-385}, {228,460}, {-237,451},
};
inline constexpr PixelPoint VD_GLYPH_BATTERY_C2[] = {
  {56,-256}, {-134,29}, {-33,106}, {-22,287}, {139,23}, {68,-40},
};
inline constexpr GlyphContour VD_GLYPH_BATTERY[] = {
  { VD_GLYPH_BATTERY_C0, std::size(VD_GLYPH_BATTERY_C0), false },
  { VD_GLYPH_BATTERY_C1, std::size(VD_GLYPH_BATTERY_C1), true },
  { VD_GLYPH_BATTERY_C2, std::size(VD_GLYPH_BATTERY_C2), false },
};
inline constexpr unsigned VD_GLYPH_BATTERY_WIDTH = 555;
inline constexpr unsigned VD_GLYPH_BATTERY_HEIGHT = 1000;

/* circle_diameter.png, 1000x846 */
inline constexpr PixelPoint VD_GLYPH_CIRCLE_DIAMETER_C0[] = {
  {-146,-423}, {-380,-229}, {-423,-78}, {-497,35}, {-426,69}, {-380,229},
  {-229,380}, {-146,423}, {146,423}, {380,229}, {426,69}, {488,48}, {497,2},
  {429,-66}, {380,-229}, {229,-380}, {146,-423},
};
inline constexpr PixelPoint VD_GLYPH_CIRCLE_DIAMETER_C1[] = {
  {-352,-146}, {-272,-266}, {-146,-352}, {109,-352}, {309,-192}, {352,-42},
  {328,-17}, {-328,-17},
};
inline constexpr PixelPoint VD_GLYPH_CIRCLE_DIAMETER_C2[] = {
  {-352,146}, {-328,54}, {328,54}, {355,85}, {309,192}, {109,352},
  {-146,352}, {-266,272},
};
inline constexpr GlyphContour VD_GLYPH_CIRCLE_DIAMETER[] = {
  { VD_GLYPH_CIRCLE_DIAMETER_C0, std::size(VD_GLYPH_CIRCLE_DIAMETER_C0), false },
  { VD_GLYPH_CIRCLE_DIAMETER_C1, std::size(VD_GLYPH_CIRCLE_DIAMETER_C1), true },
  { VD_GLYPH_CIRCLE_DIAMETER_C2, std::size(VD_GLYPH_CIRCLE_DIAMETER_C2), true },
};
inline constexpr unsigned VD_GLYPH_CIRCLE_DIAMETER_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_CIRCLE_DIAMETER_HEIGHT = 846;

/* circle_delta.png, 769x1000 */
inline constexpr PixelPoint VD_GLYPH_CIRCLE_DELTA_C0[] = {
  {-45,-500}, {-148,-350}, {-382,416}, {-331,500}, {301,500}, {384,416},
  {318,152}, {251,46}, {217,-116}, {150,-221}, {78,-458}, {47,-500},
};
inline constexpr PixelPoint VD_GLYPH_CIRCLE_DELTA_C1[] = {
  {-3,-400}, {53,-219}, {120,-113}, {153,49}, {220,155}, {253,316},
  {290,361}, {273,400}, {-284,383}, {-50,-347},
};
inline constexpr GlyphContour VD_GLYPH_CIRCLE_DELTA[] = {
  { VD_GLYPH_CIRCLE_DELTA_C0, std::size(VD_GLYPH_CIRCLE_DELTA_C0), false },
  { VD_GLYPH_CIRCLE_DELTA_C1, std::size(VD_GLYPH_CIRCLE_DELTA_C1), true },
};
inline constexpr unsigned VD_GLYPH_CIRCLE_DELTA_WIDTH = 769;
inline constexpr unsigned VD_GLYPH_CIRCLE_DELTA_HEIGHT = 1000;

/* drift_angle.png, 1000x579 */
inline constexpr PixelPoint VD_GLYPH_DRIFT_ANGLE_C0[] = {
  {482,-289}, {465,-289}, {400,-215}, {373,-209}, {150,-3}, {122,3},
  {-188,285}, {476,286}, {481,257}, {444,238}, {444,164}, {424,143},
  {405,48}, {328,-69}, {328,-105}, {498,-256},
};
inline constexpr PixelPoint VD_GLYPH_DRIFT_ANGLE_C1[] = {
  {407,183}, {394,251}, {-76,243}, {280,-77}, {368,48}, {387,162},
};
inline constexpr PixelPoint VD_GLYPH_DRIFT_ANGLE_C2[] = {
  {-500,-270}, {-476,-236}, {-217,-114}, {-193,-85}, {-228,-32}, {-219,-19},
  {-2,-27}, {-122,-211}, {-185,-137}, {-463,-289},
};
inline constexpr GlyphContour VD_GLYPH_DRIFT_ANGLE[] = {
  { VD_GLYPH_DRIFT_ANGLE_C0, std::size(VD_GLYPH_DRIFT_ANGLE_C0), false },
  { VD_GLYPH_DRIFT_ANGLE_C1, std::size(VD_GLYPH_DRIFT_ANGLE_C1), true },
  { VD_GLYPH_DRIFT_ANGLE_C2, std::size(VD_GLYPH_DRIFT_ANGLE_C2), false },
};
inline constexpr unsigned VD_GLYPH_DRIFT_ANGLE_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_DRIFT_ANGLE_HEIGHT = 579;

/* Ve.png, 1000x790 */
inline constexpr PixelPoint VD_GLYPH_EAS_C0[] = {
  {135,-112}, {38,-15}, {13,59}, {13,197}, {38,271}, {187,395}, {395,395},
  {469,370}, {469,283}, {327,304}, {286,329}, {160,279}, {127,178},
  {143,162}, {492,160}, {500,36}, {475,-38}, {349,-139}, {187,-139},
};
inline constexpr PixelPoint VD_GLYPH_EAS_C1[] = {
  {-500,-395}, {-500,-350}, {-479,-341}, {-477,-292}, {-430,-218},
  {-407,-106}, {-360,-32}, {-360,11}, {-314,84}, {-290,197}, {-240,296},
  {-137,300}, {-36,81}, {-13,-32}, {34,-106}, {127,-395}, {13,-395},
  {13,-341}, {-34,-267}, {-57,-154}, {-104,-81}, {-127,32}, {-183,139},
  {-246,32}, {-269,-81}, {-385,-341}, {-385,-395},
};
inline constexpr PixelPoint VD_GLYPH_EAS_C2[] = {
  {125,42}, {189,-48}, {323,-48}, {407,61}, {143,71},
};
inline constexpr GlyphContour VD_GLYPH_EAS[] = {
  { VD_GLYPH_EAS_C0, std::size(VD_GLYPH_EAS_C0), false },
  { VD_GLYPH_EAS_C1, std::size(VD_GLYPH_EAS_C1), false },
  { VD_GLYPH_EAS_C2, std::size(VD_GLYPH_EAS_C2), true },
};
inline constexpr unsigned VD_GLYPH_EAS_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_EAS_HEIGHT = 790;

/* flight_level.png, 1000x765 */
inline constexpr PixelPoint VD_GLYPH_FLIGHT_LEVEL_C0[] = {
  {-64,-378}, {-498,-372}, {-491,378}, {-450,367}, {-447,23}, {-147,12},
  {-132,-10}, {-147,-38}, {-439,-41}, {-447,-319}, {-68,-330},
};
inline constexpr PixelPoint VD_GLYPH_FLIGHT_LEVEL_C1[] = {
  {61,-378}, {55,372}, {489,378}, {485,330}, {105,319}, {103,-367},
};
inline constexpr GlyphContour VD_GLYPH_FLIGHT_LEVEL[] = {
  { VD_GLYPH_FLIGHT_LEVEL_C0, std::size(VD_GLYPH_FLIGHT_LEVEL_C0), false },
  { VD_GLYPH_FLIGHT_LEVEL_C1, std::size(VD_GLYPH_FLIGHT_LEVEL_C1), false },
};
inline constexpr unsigned VD_GLYPH_FLIGHT_LEVEL_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_FLIGHT_LEVEL_HEIGHT = 765;

/* g-load.png, 1000x668 */
inline constexpr PixelPoint VD_GLYPH_G_LOAD_C0[] = {
  {-500,-11}, {-470,96}, {-314,253}, {-127,334}, {153,334}, {230,308},
  {365,227}, {429,158}, {470,176}, {474,118}, {500,90}, {498,36}, {464,28},
  {354,81}, {369,124}, {288,203}, {177,259}, {104,259}, {74,285}, {-74,285},
  {-228,233}, {-314,178}, {-395,96}, {-455,-17},
};
inline constexpr PixelPoint VD_GLYPH_G_LOAD_C1[] = {
  {74,-330}, {67,-9}, {115,-13}, {115,-240}, {211,-304}, {269,-272},
  {271,-39}, {316,-4}, {346,-39}, {346,-216}, {318,-298}, {282,-332},
  {157,-332}, {130,-308},
};
inline constexpr PixelPoint VD_GLYPH_G_LOAD_C2[] = {
  {-67,-334}, {-89,-319}, {-89,-167}, {-63,-139}, {-63,13}, {-37,47},
  {-37,113}, {-65,161}, {5,253}, {61,139}, {14,120}, {-14,32}, {-40,-319},
};
inline constexpr GlyphContour VD_GLYPH_G_LOAD[] = {
  { VD_GLYPH_G_LOAD_C0, std::size(VD_GLYPH_G_LOAD_C0), false },
  { VD_GLYPH_G_LOAD_C1, std::size(VD_GLYPH_G_LOAD_C1), false },
  { VD_GLYPH_G_LOAD_C2, std::size(VD_GLYPH_G_LOAD_C2), false },
};
inline constexpr unsigned VD_GLYPH_G_LOAD_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_G_LOAD_HEIGHT = 668;

/* yaw.png, 868x1000 */
inline constexpr PixelPoint VD_GLYPH_HEADING_C0[] = {
  {-375,-469}, {-401,-427}, {-65,36}, {-287,212}, {-320,208}, {-390,135},
  {-423,135}, {-434,164}, {-375,282}, {-265,366}, {-232,366}, {-221,337},
  {-276,274}, {-274,219}, {-71,126}, {-21,80}, {386,500}, {410,500},
  {432,454}, {177,151}, {168,113}, {-113,-192}, {-122,-230},
};
inline constexpr PixelPoint VD_GLYPH_HEADING_C1[] = {
  {-36,-500}, {-34,-377}, {-14,-377}, {8,-447}, {52,-373}, {85,-373},
  {96,-500}, {67,-500}, {56,-423}, {19,-454}, {14,-500},
};
inline constexpr PixelPoint VD_GLYPH_HEADING_C2[] = {
  {153,-100}, {210,-56}, {227,-69}, {212,-104},
};
inline constexpr GlyphContour VD_GLYPH_HEADING[] = {
  { VD_GLYPH_HEADING_C0, std::size(VD_GLYPH_HEADING_C0), false },
  { VD_GLYPH_HEADING_C1, std::size(VD_GLYPH_HEADING_C1), false },
  { VD_GLYPH_HEADING_C2, std::size(VD_GLYPH_HEADING_C2), false },
};
inline constexpr unsigned VD_GLYPH_HEADING_WIDTH = 868;
inline constexpr unsigned VD_GLYPH_HEADING_HEIGHT = 1000;

/* ias.png, 1000x588 */
inline constexpr PixelPoint VD_GLYPH_IAS_C0[] = {
  {-382,279}, {-372,294}, {-292,292}, {-286,248}, {-233,156}, {-2,156},
  {30,189}, {60,294}, {392,294}, {436,271}, {500,186}, {498,66}, {372,-38},
  {317,-38}, {194,-79}, {186,-184}, {238,-217}, {371,-217}, {454,-179},
  {459,-268}, {410,-276}, {402,-294}, {207,-294}, {199,-276}, {133,-251},
  {89,-186}, {89,-70}, {153,-4}, {256,38}, {371,58}, {403,91}, {400,171},
  {351,217}, {258,236}, {235,217}, {179,217}, {110,171}, {-70,-294},
  {-166,-294}, {-186,-209}, {-225,-146}, {-225,-110}, {-264,-48}, {-264,-12},
  {-304,50}, {-323,145},
};
inline constexpr PixelPoint VD_GLYPH_IAS_C1[] = {
  {-500,-294}, {-500,284}, {-413,294}, {-403,-294},
};
inline constexpr PixelPoint VD_GLYPH_IAS_C2[] = {
  {-120,-176}, {-29,32}, {-42,79}, {-194,79}, {-207,66}, {-207,32},
  {-168,-30},
};
inline constexpr GlyphContour VD_GLYPH_IAS[] = {
  { VD_GLYPH_IAS_C0, std::size(VD_GLYPH_IAS_C0), false },
  { VD_GLYPH_IAS_C1, std::size(VD_GLYPH_IAS_C1), false },
  { VD_GLYPH_IAS_C2, std::size(VD_GLYPH_IAS_C2), true },
};
inline constexpr unsigned VD_GLYPH_IAS_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_IAS_HEIGHT = 588;

/* pitch.png, 1000x501 */
inline constexpr PixelPoint VD_GLYPH_PITCH_C0[] = {
  {380,-247}, {237,-247}, {237,-233}, {287,-217}, {245,-175}, {158,-132},
  {118,-165}, {206,-213}, {205,-230}, {104,-189}, {89,-154}, {26,-170},
  {1,-143}, {-7,-79}, {-282,136}, {-322,133}, {-402,55}, {-372,2}, {-434,39},
  {-458,24}, {-500,69}, {-500,125}, {-461,186}, {-460,225}, {-433,250},
  {-338,231}, {-283,177}, {-179,132}, {-148,100}, {226,-80}, {362,-197},
};
inline constexpr PixelPoint VD_GLYPH_PITCH_C1[] = {
  {470,-93}, {461,-30}, {474,-21}, {482,-83},
};
inline constexpr PixelPoint VD_GLYPH_PITCH_C2[] = {
  {412,-247}, {404,-223}, {436,-175}, {444,-201},
};
inline constexpr GlyphContour VD_GLYPH_PITCH[] = {
  { VD_GLYPH_PITCH_C0, std::size(VD_GLYPH_PITCH_C0), false },
  { VD_GLYPH_PITCH_C1, std::size(VD_GLYPH_PITCH_C1), false },
  { VD_GLYPH_PITCH_C2, std::size(VD_GLYPH_PITCH_C2), false },
};
inline constexpr unsigned VD_GLYPH_PITCH_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_PITCH_HEIGHT = 501;

/* speed_to_fly.png, 1000x613 */
inline constexpr PixelPoint VD_GLYPH_SPEED_TO_FLY_C0[] = {
  {-376,-307}, {-384,-288}, {-452,-262}, {-497,-152}, {-452,-46}, {-365,-2},
  {-198,43}, {-154,87}, {-130,172}, {-178,242}, {-290,286}, {-391,262},
  {-435,218}, {-459,133}, {-486,104}, {-498,172}, {-454,259}, {-386,305},
  {-204,305}, {-135,259}, {-91,172}, {-91,112}, {-115,66}, {-244,-20},
  {-304,-20}, {-411,-65}, {-457,-157}, {-435,-220}, {-365,-267}, {-244,-267},
  {-198,-244}, {-151,-174}, {-141,-124}, {-113,-131}, {-112,-174},
  {-135,-220}, {-234,-307},
};
inline constexpr PixelPoint VD_GLYPH_SPEED_TO_FLY_C1[] = {
  {497,-284}, {158,-279}, {159,302}, {195,274}, {197,27}, {410,19}, {439,-9},
  {428,-22}, {204,-22}, {197,-239}, {471,-247},
};
inline constexpr PixelPoint VD_GLYPH_SPEED_TO_FLY_C2[] = {
  {-11,-247}, {-28,-235}, {-28,295}, {-6,307}, {11,295}, {11,-90}, {91,-116},
  {62,-143}, {13,-152}, {11,-235},
};
inline constexpr GlyphContour VD_GLYPH_SPEED_TO_FLY[] = {
  { VD_GLYPH_SPEED_TO_FLY_C0, std::size(VD_GLYPH_SPEED_TO_FLY_C0), false },
  { VD_GLYPH_SPEED_TO_FLY_C1, std::size(VD_GLYPH_SPEED_TO_FLY_C1), false },
  { VD_GLYPH_SPEED_TO_FLY_C2, std::size(VD_GLYPH_SPEED_TO_FLY_C2), false },
};
inline constexpr unsigned VD_GLYPH_SPEED_TO_FLY_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_SPEED_TO_FLY_HEIGHT = 613;

/* tas.png, 1000x578 */
inline constexpr PixelPoint VD_GLYPH_TAS_C0[] = {
  {-38,-289}, {-96,-164}, {-96,-127}, {-134,-67}, {-134,-30}, {-173,29},
  {-192,124}, {-230,183}, {-248,283}, {-216,263}, {-193,183}, {-142,95},
  {91,98}, {116,127}, {137,223}, {189,289}, {219,270}, {243,287}, {394,287},
  {437,265}, {500,181}, {498,83}, {417,2}, {217,-61}, {173,-109}, {173,-183},
  {195,-226}, {242,-252}, {356,-252}, {441,-188}, {444,-127}, {465,-116},
  {481,-127}, {481,-183}, {458,-226}, {383,-289}, {232,-289}, {136,-202},
  {136,-88}, {200,-22}, {356,18}, {437,59}, {463,106}, {460,186}, {394,250},
  {338,250}, {304,270}, {193,223}, {153,143}, {153,106}, {96,8}, {96,-29},
  {57,-88}, {38,-183}, {-20,-289},
};
inline constexpr PixelPoint VD_GLYPH_TAS_C1[] = {
  {-481,-289}, {-500,-250}, {-339,-252}, {-327,-239}, {-327,278}, {-299,287},
  {-290,-239}, {-277,-252}, {-128,-250}, {-118,-263}, {-137,-289},
};
inline constexpr PixelPoint VD_GLYPH_TAS_C2[] = {
  {-31,-212}, {59,-29}, {59,8}, {79,34}, {70,56}, {-134,50},
};
inline constexpr GlyphContour VD_GLYPH_TAS[] = {
  { VD_GLYPH_TAS_C0, std::size(VD_GLYPH_TAS_C0), false },
  { VD_GLYPH_TAS_C1, std::size(VD_GLYPH_TAS_C1), false },
  { VD_GLYPH_TAS_C2, std::size(VD_GLYPH_TAS_C2), true },
};
inline constexpr unsigned VD_GLYPH_TAS_WIDTH = 1000;
inline constexpr unsigned VD_GLYPH_TAS_HEIGHT = 578;

/* true_course.png, 769x1000 */
inline constexpr PixelPoint VD_GLYPH_TRUE_COURSE_C0[] = {
  {-45,-500}, {-148,-350}, {-382,416}, {-337,497}, {-234,500}, {-39,338},
  {31,333}, {231,497}, {301,500}, {384,416}, {318,152}, {251,46}, {217,-116},
  {150,-221}, {78,-458}, {47,-500},
};
inline constexpr PixelPoint VD_GLYPH_TRUE_COURSE_C1[] = {
  {-3,-400}, {53,-219}, {120,-113}, {153,49}, {220,155}, {253,316},
  {290,361}, {273,400}, {6,205}, {-262,400}, {-284,389}, {-50,-347},
};
inline constexpr GlyphContour VD_GLYPH_TRUE_COURSE[] = {
  { VD_GLYPH_TRUE_COURSE_C0, std::size(VD_GLYPH_TRUE_COURSE_C0), false },
  { VD_GLYPH_TRUE_COURSE_C1, std::size(VD_GLYPH_TRUE_COURSE_C1), true },
};
inline constexpr unsigned VD_GLYPH_TRUE_COURSE_WIDTH = 769;
inline constexpr unsigned VD_GLYPH_TRUE_COURSE_HEIGHT = 1000;

