---
on:
  workflow_dispatch:
  push:
    paths:
      - 'doc/**'
      - '.github/workflows/build-docs.yml'
    branches:
      - master
      - dev-branch
  pull_request:
    paths:
      - 'doc/**'
      - '.github/workflows/build-docs.yml'
    branches:
      - master
      - dev-branch
env:
  TARGET:
  TARGET_FINAL: OpenSoar-docs
  TARGET_EXT: pdf
  NDK:
jobs:
  opensoar-compile:
    runs-on: ubuntu-latest

    steps:
     - id: checkout
       uses: actions/checkout@v4
       with:
         submodules: false
     - id: repository
       uses: ASzc/change-string-case-action@v6
       with:
         string: ${{ github.repository }}
     - name: find githash
       run: |
         echo "git_hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
         
     - name: Install dependencies
       run: |
         sudo apt-get update
         sudo apt-get install -y --no-install-recommends \
           make \
           python3 \
           librsvg2-bin xsltproc \
           texlive \
           texlive-latex-extra \
           texlive-luatex \
           texlive-lang-french \
           texlive-lang-polish \
           texlive-lang-portuguese \
           texlive-lang-german \
           liblocale-po-perl

     - name: OpenSoar generate Docs
       run: |
         make manual V=2

     - name: upload artifact
       uses: actions/upload-artifact@v4
       with:
         name: ${{ env.TARGET_FINAL }}-${{ env.git_hash }}
         path: output/${{ env.TARGET }}/*.${{ env.TARGET_EXT }}
